version: '2'
services:
  {service_name}:
    restart: unless-stopped
    build:
      context: worker
      args:
        - buildbot_server
        - buildbot_port
        - buildbot_password
        - buildworker_name=buildworker_{service_name}
        - L32= # Put `linux32` here if we're 32-bit
